apiVersion: v1
baseDomain: <BASE_DOMAIN>
compute:
  - name: worker
    replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: <CLUSTER_NAME>
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: <PXE_SUBNET> # exp: 192.168.20.0/24
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
proxy:
  httpProxy: http://<PXE_SERVER_IP>:3128
  httpsProxy: http://<PXE_SERVER_IP>:3128
  noProxy: .cluster.local,.svc,localhost,127.0.0.1,10.128.0.0/14,172.30.0.0/16,<PXE_SUBNET>,.lab.local
platform:
  none: {}
pullSecret: '<YOUR_PULL_SECRET_JSON>'
sshKey: |
  <YOUR_SSH_PUBLIC_KEY>
